markdown: kramdown
# Disable default theme to avoid header/nav injection
theme: null
# No additional plugins needed
plugins: []

# Ensure every page renders with the minimal layout
defaults:
  - scope:
      path: ""
    values:
      layout: plain 